<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<!-- NuGet metadata -->
		<PackageId>FpFilters</PackageId>
		<Authors>Andrei Ignat</Authors>
		<Company>Andrei Ignat</Company>
		<Description>Filters for LINQ and functional programming in C#.</Description>
		<PackageTags>filters;linq;functional;fp;dotnet;utility</PackageTags>
		<RepositoryUrl>https://github.com/ignatandrei/Filters</RepositoryUrl>
		<PackageProjectUrl>https://github.com/ignatandrei/Filters</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Copyright>Copyright (c) 2024 Andrei Ignat</Copyright>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>
	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="" />
		<None Include="LICENSE" Pack="true" PackagePath="" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

</Project>
