<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <!-- NuGet metadata -->
    <PackageId>FpFilters</PackageId>
    <Version>1.0.0</Version>
    <Authors>Andrei Ignat</Authors>
    <Company>Andrei Ignat</Company>
    <Description>Filters for LINQ and functional programming in C#.</Description>
    <PackageTags>filters;linq;functional;fp;dotnet;utility</PackageTags>
    <RepositoryUrl>https://github.com/ignatandrei/Filters</RepositoryUrl>
    <PackageProjectUrl>https://github.com/ignatandrei/Filters</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Copyright (c) 2024 Andrei Ignat</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
