
name: Test with Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_with_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
      - name: Run tests with coverage
        shell: pwsh
        run: src/csharp/run-tests-with-coverage.ps1
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: src/csharp/FpFilters.Tests/TestResults/CoverageReport/
